# Generated by Django 2.1.4 on 2018-12-24 18:13

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('no_levels', 'Please select Level'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('hnd', 'Higher National Diploma (HND)'), ('degree', 'Degree')], default=('no_levels', 'Please select Level'), max_length=50, validators=[courses.validators.defaultLevel])),
                ('fee', models.FloatField()),
                ('installment', models.IntegerField()),
                ('register', models.DateField(auto_now_add=True)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
